### ISSUE TITLE
Enable Security Advisories / Security Contact

### ISSUE THREAD

**Issue by R3x** [rstudio/shiny-workflows#16]
Hello,

I would like to report a security vulnerability in private, I was not able to find a security contact for this repository and there is no security policy and private reporting is disabled as well. What would be a good contact to reach out to? Or would you be open to enabling private vulnerability reporting for the repository?

**Comment by schloerke** [comment]
Hi @R3x. Please send me an email at barret@posit.co. Thank you

**Comment by schloerke** [comment]
Hi @R3x. I've enabled submitting security vulnerabilities in private. Please submit here: https://github.com/rstudio/shiny-workflows/security/advisories . Thank you!
