### ISSUE TITLE
Windows 4.3 needs tools 43, not 42

### ISSUE THREAD

**Issue by schloerke** [rstudio/shiny-workflows#34]
I am sorry about the windows install failures. I'll try to fix that tomorrow. Looks like it's trying to install rtools 4.2 when it needs 4.3

_Originally posted by @schloerke in https://github.com/rstudio/leaflet/pull/911#issuecomment-2024204766_

**Comment by olivroy** [comment]
Also, would be great to update to checkout@v4 to avoid node16 failures if possible. 

https://github.com/rstudio/leaflet/actions/runs/8460507256

![image](https://github.com/rstudio/shiny-workflows/assets/52606734/3253098d-e947-44fd-ab0b-0604ca622d32)
